name: Build, Scan, and Deploy Portfolio App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t JTMassa/ciportfolio .
      - name: list images
        run: docker images
  
    
       

 
     