name: Build, Scan, and Deploy Portfolio App
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: uptime
        run: uptime
      - name: Number of processors
        run: nproc
  test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
       - name: Hello 
         run: echo "Hello, world!"
    
       

 
     